name: Getting started

on:
 push:
  branches: [ main ]

jobs:
 first_job:
  runs-on: ubuntu-latest
  steps:
   - uses: action/checkout@main
   - name: this stage is for staging the code.
     run: |
         echo "Staging process start...."  
         aws s3 cp ./index.html $AWS_S3_BUCKET
     
  
