name: Getting started

on:
 push:
  branches: 
  - main 

jobs:
 first_job:
  runs-on: self-hosted
  steps:
   - uses: action/checkout@v1
   - name: this stage is for staging the code.
     run: |
        aws s3 ls
        ls
        pwd
        aws s3 cp index.html s3://"${{secrets.AWS_S3_BUCKET}}"
