name: Getting started

on:
 push:
  branches: [ main ]

jobs:
 first_job:
  runs-on: ubuntu-latest
  steps:
   - uses: action/checkout@main
   - name: this stage is for staging the code.
     run: |
        aws s3 ls
        ls
        pwd
        aws s3 cp index.html s3://forlearn   
